### ISSUE TITLE
Use optparse-generic for pgminer's command line

### ISSUE THREAD

**Issue by snowleopard** [tuura/process-mining#10]
Let's add proper support for command line options in `pgminer` using this nice package:

http://www.haskellforall.com/2016/02/auto-generate-command-line-interface.html

@jrbeaumont would you like to try it? Feel free to ask questions if you come across any difficulties.

**Comment by jrbeaumont** [comment]
@snowleopard I will give it a try yes. Thank you, I could do with the practice. I'll have a read and see what I think and let you know if I'm struggling.

**Comment by snowleopard** [comment]
Awesome, thanks!

**Comment by jrbeaumont** [comment]
So I have included the package as part of the cabal file.

Would you prefer to have `split` as a command, or keep it as `-split`?

**Comment by snowleopard** [comment]
I think we can use more a common double dash `--split` (perhaps, with a shorter synonym `-s`), which should translate to a `split :: Bool` setting in the parsed options, by default be equal to `False`.

Is this possible?

**Comment by jrbeaumont** [comment]
It seems so, I will have a go.

**Comment by jrbeaumont** [comment]
I am assuming you would prefer it to be in a style of:
`./pgminer --split L1.tr L1-extracted.cpog`
?

At the moment, I am struggling to find a way to do this without having:
`./pgminer --split --inLog L1.tr --outLog L1-extracted.cpog`

**Comment by snowleopard** [comment]
Actually, I think I'll prefer the usual `-o` parameter (note, without `--inLog`):

```
./pgminer --split L1.tr -o L1-extracted.cpog
```

Which could probably also have a longer synonym `--output`.

If `-o` is not given, then we could probably just print out the result on `stdout`. What we are doing currently is a bit non-standard and may be surprising to users.

**Comment by snowleopard** [comment]
By the way, we don't have to use `optparse-generic`. If it doesn't provide enough flexibility, we may need to look into other libraries. For example, I use `System.Console.GetOpt` in `shaking-up-ghc` project, see this file in particular: https://github.com/snowleopard/shaking-up-ghc/blob/master/src/CmdLineFlag.hs. It's quite powerful, albeit not as easy to use as `optparse-generic`.

**Comment by jrbeaumont** [comment]
The issue with `optparse-generic` is that it seems we can only have `--` flags. And I don't think it's possible to have synonyms. So we can only have;
`--split` or `--s`
`--inputLog` or `--i`
`--output` or `--o`. 

It is possible to take in parameters without needing the flags, but in this case, all parameters would need to be done in this way. For example:
`./pgminer True L1.tr L1-out.cpog`

In this case it's possible to not need to specify the output file, but I believe the Boolean must be stated, which isn't particularly nice to use. 

I think it's ease of use is great, and if you just want to stick to single name `--` flags then I can sort that fairly easily. But if we want some options then we may have to upgrade to `System.Console.GetOpt`, which may take me a little while.

**Comment by jrbeaumont** [comment]
If we don't necessarily need the `--` flags it is possible to take in something like split as a string, then test to see if it is either `split` or `s`, possible with `--` or `-` but this would mean that the help and usage prompts would be confusing

**Comment by jrbeaumont** [comment]
I'm going to make a decision on this and try and work with `System.Console.GetOpt`. 
It may be more complicated but I think the possibilities it gives us is much better.

**Comment by snowleopard** [comment]
Thanks @jrbeaumont! I agree with your decision. I think `System.Console.GetOpt` is not fundamentally more difficult to use, but it does require writing more code. Thinking longer term, if `pgminer` gets more options as we develop it, we better start with a more flexible approach.

**Comment by jrbeaumont** [comment]
@snowleopard 
I have preliminarily added support using `System.Console.GetOpt`. 

Feel free to test it from https://github.com/jrbeaumont/process-mining.git

It isn't complete, but currently the command line options are:

`-s/--split` 
`-i/--input fileName`
`-o/--output fileName`

All work as expected. 

A few points though:
- I cannot find a way to take in a file path for the input event log without needing the `-i` or `--input`. Do you have any ideas about this?
- If `-i` or `--input` is not used, the tool will fail. I will however add a validation step for this.
- If `-o` or `--output` is not used, it currently defaults to the input event log file path, with the extension replaced by `.cpog`.
- There are no help or usage messages currently, I need to work those out still but that shouldn't be too difficult. I will also ensure that these messages occur at relevant times, such as when there are unrecognised commands, or at tool failure.
- I aim to try and refactor the additions I have made, and contain the command line code in it's own file.

Any thoughts?

**Comment by snowleopard** [comment]
Great start, I only have a few minor suggestions:
- To avoid requiring `-i` I suggest to allow one non-option argument in the command line. Non-option arguments are returned as the second element of the `getOpt` triple. Getting an empty list should be equivalent to omitting the input file, getting more than one element in the list there should be an error.
- Use `Permute` instead of `RequireOrder` so that you can mix options and non-options in arbitrary order.
- Have a look at section 3.2 here: https://wiki.haskell.org/High-level_option_handling_with_GetOpt. I think it would be great to adopt the `optInput :: IO String` and `optOutput :: String -> IO ()` idea using `getContents` and `putStr` as default values -- in this way if no input file is given then a user can simply quickly type it into `stdin`. And if no output file is given the result will be printed to `stdout`. Silently producing a `.cpog` file may be surprising as it can overwrite user files.

**Comment by snowleopard** [comment]
I think we can close this one. Thanks @jrbeaumont!
