### ISSUE TITLE
Instructions for building and running PGminer

### ISSUE THREAD

**Issue by snowleopard** [tuura/process-mining#6]
We should add a section on `PGminer` to the `README`, explaining how to build it from sources and how to run it on simple event logs, perhaps, using the examples from the ToPNoC paper.

@jrbeaumont Could you help with that?

**Comment by jrbeaumont** [comment]
I will get on this right away.

**Comment by jrbeaumont** [comment]
I will at some point add some instructions to the cabal file to include a method of building a PGminer executable using cabal to give extra options.

**Comment by snowleopard** [comment]
I did some further work on the `README`. Let's keep this issue open until we finalise the Cabal section.

**Comment by jrbeaumont** [comment]
I have added to the `pgminer.cabal` file to build an executable using cabal. However, this executable is placed in `dist/build/pgminer/`. I am not overly sure how to move this to the top level, but it works at least. 

Any ideas? I will also add an instruction for this to the `README`.

**Comment by snowleopard** [comment]
@jrbeaumont Is it possible to run it using cabal as well? Something like `cabal run pgminer`?

**Comment by jrbeaumont** [comment]
Yes it is. I can add this to the `README` instead. It would make sense if you're building it with cabal to run it with cabal.

**Comment by snowleopard** [comment]
@jrbeaumont Yes, I think so. Make sure to test running it with command line arguments. You might need to use `--` as a separator of command line arguments (to separate from the ones passed to cabal itself).

**Comment by jrbeaumont** [comment]
@snowleopard This works correctly. I will update the `README` and send a PR.

**Comment by snowleopard** [comment]
Right, I think we can now close the issue.

We still haven't explained how to use `-split` and what it means, but I am actually not very happy about the current implementation, so maybe we should improve it first.

We could also add a proper support for command line arguments using something like this: http://www.haskellforall.com/2016/02/auto-generate-command-line-interface.html, but let's do this separately from this issue.

**Comment by jrbeaumont** [comment]
My next question was going to be "Shall I add some information on `-split`?".

I can add some information anyway if you would like, but if you'd like to change the implementation then it isn't a pressing issues. 

Some proper support for command line arguments might be good, but I'm not sure it will change how it is used with Cabal. But as you say, this is for a different issue.

**Comment by snowleopard** [comment]
@jrbeaumont I think ideally we need a separate `doc/pgminer.md` for PGminer, where we will explain all options, etc. I will also upload there the ToPNoC article into `doc` once it is accepted.

**Comment by jrbeaumont** [comment]
@snowleopard That's a good idea, keep more information in one place. We could possibly change the `README` to simply build and run instructions, and move examples into `doc/pgminer.md`. But this is a discussion for another issue.
